<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-13T11:30:04 IST" name="Default suite" finished-at="2023-01-13T11:30:26 IST" duration-ms="21554">
    <groups>
    </groups>
    <test started-at="2023-01-13T11:30:04 IST" name="Default test" finished-at="2023-01-13T11:30:26 IST" duration-ms="21554">
      <class name="testcase.TestCase">
        <test-method is-config="true" signature="Aobjects()[pri:0, instance:testcase.TestCase@422b8438]" started-at="2023-01-13T11:30:04 IST" name="Aobjects" finished-at="2023-01-13T11:30:07 IST" duration-ms="2694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Aobjects -->
        <test-method signature="Btestloginpage()[pri:0, instance:testcase.TestCase@422b8438]" started-at="2023-01-13T11:30:07 IST" name="Btestloginpage" description="Login page" finished-at="2023-01-13T11:30:08 IST" duration-ms="749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Btestloginpage -->
        <test-method signature="Ctestbutton()[pri:0, instance:testcase.TestCase@422b8438]" started-at="2023-01-13T11:30:08 IST" name="Ctestbutton" description="Clicking on main functionality" finished-at="2023-01-13T11:30:12 IST" duration-ms="4173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Ctestbutton -->
        <test-method signature="Dresources()[pri:0, instance:testcase.TestCase@422b8438]" started-at="2023-01-13T11:30:12 IST" name="Dresources" description="Clicking on Resources" finished-at="2023-01-13T11:30:25 IST" duration-ms="13201" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [security at Sauce Labs] but found [Security at Sauce Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [security at Sauce Labs] but found [Security at Sauce Labs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcase.TestCase.Dresources(TestCase.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dresources -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcase.TestCase@422b8438]" started-at="2023-01-13T11:30:26 IST" name="teardown" finished-at="2023-01-13T11:30:26 IST" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcase.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
